services:
  mongodb:
    image: mongo
    container_name: tsp_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - tsp_data:/data/db
volumes:
  tsp_data: