services:
  mongodb:
    image: mongo
    container_name: tsp_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - tsp_data:/data/db
  tsp:
    build:
      context: .src/container/
      dockerfile: Dockerfile
    container_name: tsp
    volumes:
      - ./tsp:/app/tsp:ro
      - ./container:/app/container
    depends_on:
      - mongodb
volumes:
  tsp_data: